### PR TITLE
fix(core): remove hardcoded git domains

### LINKED ISSUE #47: Install dependency from a private server
Currently, soldeer can download and install any dependency that is public under a `zip` archive.
Would be awesome to have a way to also install private dependencies, this mostly for under development projects that are developing under the radar until the smart contracts are released.

Maybe a way to do this is to have in the install command a way to specify a user/pass/token to pull the dependency using OAuth maybe from a certain link?

Another possibility to overcome this is to have private repositories in soldeer central repository but for that we need a bit more research.

### PR DESCRIPTION
**Pull request by puuuuh**
Closes #47

### CODE REVIEW

File: crates/core/src/utils.rs [hunk 1]
```diff
@@ -84,23 +79,13 @@ pub fn check_dotfiles(files: &[PathBuf]) -> bool {
...
 /// Get the type of URL from a dependency URL.
 ///
-/// Git URLs are identified by the presence of the `git@github.com` or `git@gitlab.com` prefix, as
-/// well as HTTPS URLs which have the `github.com` or `gitlab.com` domain and a trailing `.git` in
-/// their path.
+/// Git URLs are identified by the presence of the `git@` prefix, as
+/// well as HTTPS URLs which have the trailing `.git` in their path.
 pub fn get_url_type(dependency_url: &str) -> Result<UrlType, DownloadError> {
-    if GIT_SSH_REGEX.is_match(dependency_url) {
+    if dependency_url.starts_with("git@") {
```
Comment (beeb) [inline crates/core/src/utils.rs:85]: I'm wondering if we should add a requirement that this ends with `.git`. Also, how likely is it that other servers use a different username than `git`?

File: crates/commands/tests/tests-init.rs [hunk 2]
```diff
@@ -129,7 +129,7 @@ out = "out"
 libs = ["dependencies"]
 
 [dependencies]
-forge-std = "1.9.4"
+forge-std = "1.9.5"
```
Comment (beeb) [inline crates/commands/tests/tests-init.rs:132]: This test will be made dynamic in my next PR, sorry for the unrelated breakage ^^

File: crates/core/src/utils.rs (hunk 1 above)
Comment (puuuuh) [reply crates/core/src/utils.rs:85]: we can just introduce new flag for git deps to the cli crate

**Review by beeb — CHANGES_REQUESTED** [review]
Could you update the usage guide with the necessary changes in the cli's options?

File: crates/commands/src/commands/install.rs [hunk 3]
```diff
@@ -85,6 +86,11 @@ pub struct Install {
     /// location.
     #[arg(long, value_enum)]
     pub config_location: Option<ConfigLocation>,
+
+    /// If set, this command will treat url as url to git repository
+    #[arg(long, default_value_t = false)]
+    #[builder(default)]
+    pub git: bool,
```
Comment (beeb) [inline crates/commands/src/commands/install.rs:93]: Wondering if it would make sense to have two arguments `--git` and `--url` with type String instead of a positional argument and a boolean. Because at the moment the boolean does not require that the positional argument exists, and it would improve consistency overall

**Review by beeb — APPROVED** [review]
Thanks a lot for the contribution!

**Comment by mario-eth** [comment]
Awesome work sir! ❤️ thank you!
